# Generated by Django 4.0.3 on 2022-09-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='product_id',
            new_name='product',
        ),
    ]
