# Generated by Django 4.0.3 on 2022-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_rename_users_user_alter_pricehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(),
        ),
    ]
