# Generated by Django 4.0.3 on 2022-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_rename_product_pricehistory_linked_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img_out_src',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
