# Generated by Django 4.0.3 on 2022-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_rename_image_product_img_product_img_out_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
