# Generated by Django 4.0.3 on 2022-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
