# Generated by Django 4.0.3 on 2022-09-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_alter_pricehistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desired_price',
        ),
        migrations.CreateModel(
            name='ProductToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_price', models.IntegerField()),
                ('linked_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checker.product')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checker.user')),
            ],
        ),
    ]
