# Generated by Django 4.0.3 on 2022-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_remove_user_desired_price_producttouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='producttouser',
            name='auth_token',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
