# Generated by Django 4.0.3 on 2022-09-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_remove_producttouser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttouser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttouser',
            name='auth_token',
            field=models.CharField(max_length=20),
        ),
    ]
