# Generated by Django 4.0.3 on 2022-10-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_remove_producttouser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linked_product',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='linked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_product', to='checker.product'),
        ),
    ]
