# Generated by Django 4.0.3 on 2022-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_remove_user_linked_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttouser',
            name='linked_product',
        ),
        migrations.AddField(
            model_name='producttouser',
            name='linked_product',
            field=models.ManyToManyField(to='checker.product'),
        ),
        migrations.RemoveField(
            model_name='producttouser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='producttouser',
            name='user_id',
            field=models.ManyToManyField(to='checker.user'),
        ),
    ]
