# Generated by Django 4.0.3 on 2022-10-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0015_remove_producttouser_linked_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttouser',
            name='linked_product',
        ),
        migrations.AddField(
            model_name='producttouser',
            name='linked_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='checker.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='producttouser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='producttouser',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='checker.user'),
            preserve_default=False,
        ),
    ]
