# Generated by Django 4.0.3 on 2022-10-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0016_remove_producttouser_linked_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='linked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_product', to='checker.product'),
        ),
        migrations.AlterField(
            model_name='producttouser',
            name='linked_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checker.product'),
        ),
        migrations.AlterField(
            model_name='producttouser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checker.user'),
        ),
    ]
