# Generated by Django 4.0.3 on 2022-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0018_alter_pricehistory_linked_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttouser',
            name='new_price',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
