# Generated by Django 4.0.3 on 2022-10-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0019_producttouser_new_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttouser',
            old_name='new_price',
            new_name='price_alt',
        ),
    ]
