# Generated by Django 4.0.3 on 2022-10-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0020_rename_new_price_producttouser_price_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttouser',
            name='price_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
