# Generated by Django 4.0.3 on 2022-10-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0022_alter_producttouser_auth_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name_plural': 'Price History'},
        ),
    ]
