# Generated by Django 4.0.3 on 2022-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0023_alter_pricehistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
