# Generated by Django 4.0.3 on 2022-11-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0024_alter_pricehistory_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='date',
            new_name='price_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=20, unique=True),
        ),
    ]
